# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6eebbcf64045a3d6301519526b6f6d1a17617a40c9a04d2a38cc61e4b2344616e735b520e3dbb20bf8ad8e6282b6a053e60c93f5526fbee08998a2fb48bbb6e3

test:
  secret_key_base: 121b8a87e4f88e4b9e3916cc0642ac45d43590b42711958a414141c48bcf57acd2d4f4895f8201c4c5494921f236ee7ab80edbf27bf7e9f7f484e3d04b1f109e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
